// <auto-generated />
using System;
using ConsumeRESTfulAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsumeRESTfulAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231125033337_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ConsumeRESTfulAPI.Model.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CurrentUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("DATETIME(6)");

                    b.Property<DateTime?>("InsertedDateTime")
                        .HasColumnType("DATETIME(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("DECIMAL(10, 2)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("DATETIME(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ConsumeRESTfulAPI.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CurrentUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("DATETIME(6)");

                    b.Property<DateTime?>("InsertedDateTime")
                        .HasColumnType("DATETIME(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(10, 2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("DATETIME(6)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentUserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ConsumeRESTfulAPI.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("VARCHAR(512)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("VARCHAR(512)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("VARCHAR(512)");

                    b.Property<int>("CurrentUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<DateTime?>("InsertedDateTime")
                        .HasColumnType("DATETIME(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("DECIMAL(10, 2)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("DATETIME(6)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConsumeRESTfulAPI.Model.Device", b =>
                {
                    b.HasOne("ConsumeRESTfulAPI.Model.User", "CurrentUser")
                        .WithMany()
                        .HasForeignKey("CurrentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsumeRESTfulAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConsumeRESTfulAPI.Model.Product", b =>
                {
                    b.HasOne("ConsumeRESTfulAPI.Model.User", "CurrentUser")
                        .WithMany()
                        .HasForeignKey("CurrentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentUser");
                });

            modelBuilder.Entity("ConsumeRESTfulAPI.Model.User", b =>
                {
                    b.HasOne("ConsumeRESTfulAPI.Model.User", "CurrentUser")
                        .WithMany()
                        .HasForeignKey("CurrentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentUser");
                });
#pragma warning restore 612, 618
        }
    }
}
